language: python
python:
  - "3.7"

services:
  - docker

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      before_script: pip install docker-compose
      env:
        - SECRET_KEY="supersecretkey"
        - DB_HOST="host.docker.internal"
        - DB_NAME="app"
        - DB_USER="postgres"
        - DB_PASS="supersecretpassword"
        - DB_PORT="5432"
      script:
         - docker-compose run app sh -c "python manage.py test --settings=app.settings.ci && flake8"





